name: Java CI with Maven
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Grant execute permission for Maven wrapper
        run: chmod +x ./mvnw
      - name: Run tests with secrets
        run: ./mvnw test -DTELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} -DTELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}
